# Generated by Django 4.2.7 on 2023-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_descount_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='home.product'),
        ),
    ]
