# Generated by Django 4.2.7 on 2023-12-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bannerdiscount_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerdiscount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_banner_discount', to='home.product'),
        ),
    ]
