# Generated by Django 4.2.7 on 2023-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars_percent',
            field=models.IntegerField(default=0),
        ),
    ]
