# Generated by Django 4.2.7 on 2023-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_stars_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars_percent',
            field=models.IntegerField(),
        ),
    ]
