# Generated by Django 4.2.7 on 2023-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars_percent',
        ),
    ]
