# Generated by Django 4.2.7 on 2023-12-19 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.size'),
        ),
    ]
