# Generated by Django 4.2.7 on 2023-12-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_brands_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
